spring:
  datasource:
    url: jdbc:mysql://localhost:3306/worktest4.20?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8090
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    驼峰下划线配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml